# src/agents/rollback_agent.py
"""
Rollback Agent — Automated reversion on regression detection.

Triggered by:
- Watcher detecting error_rate spike post-deploy
- Sandbox test failures on generated code
- Health check failures during canary window
- Explicit Guardian intervention (risk_score >= 0.8)

Actions:
1. Identify last-known-good state
2. Prepare git revert command
3. Create remediation SAKE task for the Intent Generator
4. Log audit trail

NOTE: This agent PROPOSES rollbacks but does not execute them directly.
Execution requires human approval unless autonomy_budget >= 0.75.

CGRF v3.0 Compliance:
- SRS Code: SRS-ROLLBACK-001
- Tier: 1 (DEVELOPMENT)
- Execution Role: INFRASTRUCTURE

@module citadel_lite.src.agents.rollback_agent
"""
from __future__ import annotations

import logging
import time
from typing import Any, Dict, List, Optional

from src.types import HandoffPacket

logger = logging.getLogger(__name__)


def _identify_failing_change(packet: HandoffPacket) -> Dict[str, Any]:
    """
    Identify which change caused the regression from pipeline state.
    """
    result = {
        "failing_commit": None,
        "failing_pr": None,
        "symptoms": [],
        "source": "unknown",
    }

    # Check Watcher for post-deploy regression signals
    watcher = packet.agent_outputs.get("watcher")
    if watcher:
        w_data = watcher.payload if hasattr(watcher, "payload") else watcher
        if w_data.get("severity") in ("critical", "warning"):
            result["symptoms"].extend(w_data.get("signals", []))
            result["source"] = "watcher"

    # Check sandbox for test failures
    sandbox = packet.agent_outputs.get("sandbox")
    if sandbox:
        s_data = sandbox.payload if hasattr(sandbox, "payload") else sandbox
        if not s_data.get("passed", True):
            result["symptoms"].append(f"sandbox_exit_{s_data.get('exit_code', -1)}")
            result["source"] = "sandbox"

    # Check merge gate for rejected merges
    merge_gate = packet.agent_outputs.get("merge_gate")
    if merge_gate:
        m_data = merge_gate.payload if hasattr(merge_gate, "payload") else merge_gate
        if m_data.get("decision") == "BLOCKED":
            result["symptoms"].append("merge_blocked")

    # Check F993 for the originating change
    f993 = packet.agent_outputs.get("f993_python") or packet.agent_outputs.get("f993")
    if f993:
        f_data = f993.payload if hasattr(f993, "payload") else f993
        if f_data.get("files"):
            result["failing_commit"] = f_data["files"][0].get("content_hash", "unknown")[:8]

    return result


def _create_remediation_spec(failure: Dict[str, Any]) -> Dict[str, Any]:
    """Create a SAKE task spec for fixing the regression."""
    symptoms = failure.get("symptoms", [])
    return {
        "filetype": "SAKE",
        "version": "1.0",
        "taskir_blocks": {
            "task_name": "RegressionFix",
            "purpose": f"Fix regression: {', '.join(symptoms[:3])}",
            "inputs": ["failing_change", "symptoms", "infrastructure_state"],
            "outputs": ["fix_patch"],
            "preconditions": "Rollback applied, system stable",
            "postconditions": "Original change works without regression",
            "algorithm_summary": "Analyze failure, apply targeted fix",
            "pseudocode": (
                f"# Symptoms: {', '.join(symptoms[:5])}\n"
                f"# Source: {failure.get('source', 'unknown')}\n"
                "# 1. Reproduce the failure\n"
                "# 2. Identify root cause\n"
                "# 3. Apply minimal fix\n"
                "# 4. Verify fix resolves symptoms"
            ),
            "design_notes": "Auto-generated by Rollback Agent",
            "complexity": "O(n)",
            "edge_cases": "Fix may introduce new issues",
            "test_spec": "All original tests pass + regression test",
            "extensibility_hooks": "post_fix",
        },
        "sake_layers": {
            "backend_layer": {
                "language": "Python",
                "framework": "Standalone",
                "entrypoint": "RegressionFix.execute",
            },
            "caps_profile": {
                "confidence": 0.6,
                "cost": 0.3,
                "latency_ms": 10000.0,
                "risk": 0.4,
                "precision": 0.7,
                "trust_score": 0.75,
                "grade": "T2",
            },
        },
        "metadata": {
            "srs_code": "F993",
            "generator": "rollback_agent",
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "reflex_group": "REMEDIATION",
            "code_gen_hooks": ["post_generate", "post_test"],
        },
    }


def run_rollback_agent(packet: HandoffPacket) -> Dict[str, Any]:
    """
    Evaluate whether a rollback is needed and prepare the rollback plan.

    Returns:
        Dict with rollback decision, plan, and remediation task.
    """
    failure = _identify_failing_change(packet)
    symptoms = failure.get("symptoms", [])

    if not symptoms:
        return {
            "rollback_needed": False,
            "reason": "No regression symptoms detected",
            "symptoms": [],
        }

    # Determine severity of the regression
    critical_symptoms = [s for s in symptoms if "critical" in s or "crash" in s]
    is_critical = len(critical_symptoms) > 0

    # Build rollback plan
    rollback_plan = []
    if failure.get("failing_commit"):
        rollback_plan.append(
            f"git revert {failure['failing_commit']} --no-edit"
        )
    rollback_plan.extend([
        "Run test suite to verify revert is clean",
        "Deploy reverted version",
        "Monitor for 5 minutes via Watcher",
    ])

    # Create remediation task for Intent Generator
    remediation_spec = _create_remediation_spec(failure)

    return {
        "rollback_needed": True,
        "is_critical": is_critical,
        "failing_commit": failure.get("failing_commit"),
        "symptoms": symptoms,
        "symptom_count": len(symptoms),
        "source": failure.get("source", "unknown"),
        "rollback_plan": rollback_plan,
        "remediation_task_created": True,
        "remediation_sake_spec": remediation_spec,
        "requires_human": not is_critical,  # Critical = auto-rollback
        "timestamp": time.time(),
    }
